[package]
name = "6shell"
version = "0.1.0"
authors = ["lærling <laerling@posteo.de>"]

[dependencies]
conch-parser = "*"
conch-runtime = "*"
log = { version = "*", features = [ "max_level_trace", "release_max_level_info" ] }
simple_logger = "*"
tokio-core = "*"